version: "3"
services:
  nginx-react:
    image: portfolio-jake:prod
    container_name: nginx-react-app
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - 80:80
    environment:
      NODE_ENV: production